### ISSUE TITLE
Help files haven't been converted to the new help system

### ISSUE THREAD

**Issue by nhthn** [supercollider-quarks/AmbIEM#1]
Hey @dotinspace want to give this a shot? Someone asked about this on the mailing list.

**Comment by dotinspace** [comment]
Sure, I'll do some more grunt work!

**Comment by equilet** [comment]
I saw that this has been implemented in the files here (I think), but the quark install from Quarks.gui doesn't seem to have the help files implemented.  Is there version skew happening there?

**Comment by nhthn** [comment]
@equilet It should be working... have you tried updating it in Quarks.gui?

**Comment by equilet** [comment]
Yes - updated to r2832

**Comment by equilet** [comment]
Just updated to a newer rev of SC - looks like it was version skew on my end.  Sorry for the noise!
